site:
  title: Antora better-docs Template
  # the 404 page and sitemap files only get generated when the url property is set
  url: http://localhost:8000
  start_page: system::index.adoc
content:
  sources:
  - url: .
    start_path: docs
    branches: [HEAD]
ui:
  bundle:
     url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
     snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll     

asciidoc:
  attributes:
    sectanchors: true
    kroki-fetch-diagram: true
    kroki-server-url: https://kroki.io
  extensions:
  - asciidoctor-kroki
output:
  dir: ./dist/
