= Important words
:reftext: important words
:navtitle: SHALL, SHOULD and MAY
:description: The semantics of SHALL, SHOULD and MAY are defined here.
:author: jens@neuhalfen.name

The sematics of a few important words need to be defined in order to make this documentation unanimous.

This document uses the definitions of <<rfc2119>> as they are more expressive and a superset of the ISO definitions.

== Semantics according to ISO
The https://www.iso.org/foreword-supplementary-information.html[ISO defines] the following semantics:

shall:: indicates a requirement
should:: indicates a recommendation
may:: is used to indicate that something is permitted
can:: is used to indicate that something is possible, for example, that an organization or individual is able to do something

[#rfc2119]
== Semantics according to RFC 2119

https://www.ietf.org/rfc/rfc2119.txt[RFC 2119] is a superset of the ISO definition:

MUST::   This word, or the terms "REQUIRED" or "SHALL", mean that the
   definition is an absolute requirement of the specification.

MUST NOT::   This phrase, or the phrase "SHALL NOT", mean that the
   definition is an absolute prohibition of the specification.

SHOULD::   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

SHOULD NOT::   This phrase, or the phrase "NOT RECOMMENDED" mean that
   there may exist valid reasons in particular circumstances when the
   particular behavior is acceptable or even useful, but the full
   implications should be understood and the case carefully weighed
   before implementing any behavior described with this label.

MAY::   This word, or the adjective "OPTIONAL", mean that an item is
   truly optional.  One vendor may choose to include the item because a
   particular marketplace requires it or because the vendor feels that
   it enhances the product while another vendor may omit the same item.
   An implementation which does not include a particular option MUST be
   prepared to interoperate with another implementation which does
   include the option, though perhaps with reduced functionality. In the
   same vein an implementation which does include a particular option
   MUST be prepared to interoperate with another implementation which
   does not include the option (except, of course, for the feature the
   option provides.)
