@startuml "L1 - System Container Diagram"
!include <C4/C4_Container>

' several sprites for users. https://github.com/Roemer/plantuml-office
!include <office/Users/user.puml>
!include <office/Users/mobile_user.puml>
!include <office/Users/administrator.puml>
!include <office/Users/call_center_agent.puml>
!include <office/Services/email_service.puml>
!include <office/Communications/smtp_connector.puml>

LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

Person(customer, "Customer", "A customer of ACME.", $sprite="user")

Enterprise_Boundary(c0, "ACME limited") {
    Person(support_agent, "Support Agent", "Handles all customer interactions.", $sprite="call_center_agent")
    Person(admin, "Administrator", "System administrator that manages the system.", $sprite="administrator")

    Container(admin_ui, "Admin UI", "Text UI in Golang" , "Allows administrators to manage the ACME Engine.")

    Container(acme_ui, "The UI", "WebUI in React", "Central UI towards the customer.")
    Container(acme_engine, "The Engine", "C#, ASP.NET Core (REST, GraphQL)" , "Because every IT system needs a component called <i>Engine</i>.")

    System_Ext(mta, "mail.acme.com", "ACME SMTP server", $sprite="email_service")
}

System_Ext(payment, "Payment System", "Handles all payment processes.")


Rel_R(customer, support_agent, "States support request to", "Telephone")

Rel_R(customer, acme_ui, "Orders thingies using")

Rel(support_agent, acme_ui, "Looks up order information using")

Rel_R(acme_engine, mta, "Send notification emails", "SMTP(S)", $sprite="smtp_connector,scale=0.5")

Rel_D(acme_ui, acme_engine, "Drive business processes via", "GraphQL via HTTPS")

Rel_D(admin_ui, acme_engine, "Configure the system", "REST via HTTPS")

Rel_D(acme_engine, payment, "Initiate payment process in", "CSV export via ftp")

Rel_D(admin, admin_ui, "Configure the system", "HTTPS")

Lay_D(customer, acme_engine)

Lay_R(acme_ui, admin)
Lay_R(support_agent, admin_ui)
@enduml
